channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.1.4
  - pydot==3.0.4
  - torch==2.6.0
  - tqdm==4.67.1
name: mlflow-env
